znoyder/get_project_zuul_files.py
Usage:
```
usage: get_project_zuul_files.py [-h] -p PROJECT_NAME -b BRANCH_NAME -d
DESTINATION_FOLDER
get_project_zuul_files.py: error: the following arguments are required: -p/--projectname, -b/--branchname, -d/--destinationfolder
```
```
... (feature/get-zuul-files-script)$ -> flake8 --max-line-length=100 . && echo "PEP8 Passed"
```
=> New script to get zuul files from project

znoyder/browser.py
We noticed there is a single project that has no upstream
repository defined and it causes failures in filtering.
Proposed fix is to cast None in such case to string
so we can filter for it anyway.
=> Fix filtering by upstream in browser

znoyder/lib/zuul.py
'!encrypted/' is custom tag and yaml parser fails to recognize it.
Borrowed from: https://opendev.org/zuul/zuul-sphinx/commit/3ef1afe17ee74f5420247463652efd71e6f1e406
=> Make yaml parser aware of custom encrypted tag

znoyder/templater.py
Fixes issue in which sometimes job was listed multiple
times for single project.
=> Ensure job is listed in template only once.

znoyder/generator.py
For the projects where zuul config files are inside zuul.d directory
it's name should be stripped from the path.
=> Project name should be without zuul.d

znoyder/browser.py, znoyder/generator.py
Downstream templates should be using downstream
projects names in order to functional properly.
=> Switch to downstream names in templates

README.md, znoyder/browser.py
Used urllib to extract easily the project names in every URL provided by the  section of the packages.
In this way we can parse the Git URL (extracted with the net_loc) and receive the projecs (Which is the path) following the [URL Syntactic Components](https://www.rfc-editor.org/rfc/rfc1808.html#section-2.1).
=> Add projects argument under browse-osp

znoyder/browser.py, znoyder/generator.py
Some projects have different names and upsrteam repository
names. We should first take repository name as the project
name for znoyder to calculate mappings correctly.
=> Adjust upstream to downstrem name mapping

znoyder/templates/zuul-project.j2
Add python_use_pyenv variable into the zuul-project template to allow using pyenv
=> Add python_use_pyenv variable into the zuul-project template

znoyder/browser.py, znoyder/cli.py, znoyder/downloader.py, znoyder/finder.py, znoyder/generator.py, znoyder/templater.py
* Instead of parsing arguments and checking which
command was used, associate subparsers with specific module
* The commands extend the main parser with subparsers,
instead of creating their own parsers
* Subparsers are created by iterating over commands dictionary
which holds the following information: help/description string
and the module to use for extending the parser & associating
the module's main function to the subparser
=> Refactor argument parser code

.gitignore, znoyder/cli.py, znoyder/generator.py, znoyder/lib/logger.py
This introduces two cli parameters, log_mode and log_file. The first
gives the user the ability to choose whether to write the ouptut to
stderr, to a file or to both. In case file is selected, the log_file
parameter selects the path to write to.
=> Add ability to redirect generator outptut to file

znoyder/cli.py
Before the cli refactor, calling browse-osp with no command would be
manually detected and the program would exit. After the refactor that
check was lost and the program would coninue and crash due to missing
arguments. Adding required=True to the command subparser recovers the
original behavior.
=> Fix bug when calling browse-osp with no command

.gitignore, tests/__init__.py, tests/test_browser.py, tox.ini, znoyder/browser.py
Additionally:
- Fixed a few things on the 'main' function to get the test cases to pass.
- Export coverage as html for review.
- Indicate which directories should flake8 only transverse in order to avoid it from checking ignored files.
- Ignore PyCharm's cache
=> Unit testing the 'browser' module.

znoyder/cli.py
Defaults for log-mode and log-file changed but the help string was not
reflecting those changes.
=> Fix help description for logging arguments

tests/test_mapper.py, znoyder/config.yml, znoyder/generator.py, znoyder/lib/zuul.py, znoyder/mapper.py
- Jobs mapper improvements
This commit introduces changes to jobs mapper that does not
replace all jobs options in override map, but only updates
the defined values and allows us to undefine some jobs options
we may not want to keep by setting them to None (tilde ~ in YAML).
Additional unit tests were introduced to ensure the mechanism
works as expected.
This commit also solved one identified flaw in Zuul library
that caused unexpected behavior due to mess in objects references.
Further investigation and improvements to Zuul library will be
implemented in the future.
- Znoyder config update
This commit sets the config map to the currently expected state.
Only necessary set of entries is present right now.
=> Part 3 of jobs mapper implementation

znoyder/config.yml
Switch jobs which fail CI to non-voting.
In addition, add rhos-release to pep8 job in ovsdbapp since
it requires openvswitch package.
=> Update CI config

znoyder/config.yml
There are numerous of jobs that are still unstable (either
due to still missing dependencies or new issues after jobs
were moved to RHEL 9 environment). To not block the processes
yet, we mark those jobs as non-voting. An investigation
with necessary fixes will be conducted as further action.
=> Mark currently unstable jobs as non-voting

znoyder/config.yml
Add tox-based functional jobs following the same requirements used until
now, that is, only py39+ and excluding storage jobs.
=> Add functional jobs to config map

README.md, znoyder/cli.py, znoyder/config.yml, znoyder/finder.py, znoyder/generator.py, znoyder/lib/exceptions.py, znoyder/lib/zuul.py, znoyder/mapper.py, znoyder/templates/zuul-project-template.j2, znoyder/tests/test_cli.py, znoyder/tests/test_finder.py, znoyder/tests/test_mapper.py
I have no idea how this change became so big... There are just two commits:
– Rename trigger type to pipeline
In shperer the entity that aggregates a set of job that should
be launched on a specific condition was called a trigger type.
Now we know that the proper term in Zuul terminology is pipeline.
This commit updates the code to reflect that and set proper
names everywhere.
– Update config map with new terminology
After recent Zuul library update, the config map
should use the new naming convention for parameters.
TL;DR the `type` is now the `pipeline` in `config.yml`.
=> Rename trigger type to pipeline

znoyder/browser.py, znoyder/cli.py, znoyder/tests/test_browser.py
This commit introduces support for additional filterings
for browse-osp module of Znoyder, including the missing
osp-project that will be crucial for RPM-based jobs.
Jira: OSPCRE-454
=> Add support for filtering by osp-project

znoyder/config.yml, znoyder/lib/zuul.py, znoyder/mapper.py, znoyder/tests/test_mapper.py
Implement hash and eq for ZuulJob
This commit implements hash function and equality definition
for the ZuulJob object. It will be useful for identifying
existences and uniquenesses of the jobs defined.
Implement copy mechanism
This commit introduces the copy mechanism. It allows to copy jobs:
– from one pipeline to another,
– under new name.
In both variants it is possible to define jobs parameters, similarly
to how it is done with override map.
Add copy map entries to config
This commit add all check jobs to the weekly pipeline.
We will use the periodic (weekly) pipeline for monitoring
the jobs stability.
=> Implementation of copy mechanism

znoyder/generator.py, znoyder/templater.py, znoyder/templates/zuul-resources.j2
This commit introduces a new function that generates
the Zuul resources configuration file, where repositories
available for a given tenant are specified. For supporting
multiple OSP releases, we need to automate this file
generation as well.
=> Add Zuul resources generation

znoyder/config.yml
This is required for running the unit tests for the
project tripleo-heat-agents:
"/usr/bin/bash: line 1: testr: command not found"
=> [tripleo-heat-agents] Install testrepository

znoyder/config.yml
This change makes sure we install the required packages
and adjust horizon lib path for having an operational CI
for barbicanclient.
=> [barbicanclient] Fix OSP 17.0 CI

znoyder/config.yml
Add missing dependencies for running successfully py39 unit tests.
=> Fix neutron config by adding dependencies

znoyder/config.yml
This is required for running successfully py39 unit tests.
=> Fix mistralclient config by adding dependencies

znoyder/config.yml
In order to run successfully py39 unit tests.
=> Fix ceilometer config by adding dependencies

znoyder/config.yml
Add installation of python3-hacking in opestack-tempest
config section for CI to pass successfully.
=> Fix openstack-tempest config by adding a dependency

znoyder/config.yml
Required for running py39 tests successfully.
=> Fix python-os-win config by adding missing dependencies

znoyder/config.yml
Add missing dependencies to manila config for py39 tests to
pass successfully.
=> Fix Manila config by adding missing dependencies

tools/generate-components-projects-dict.sh, znoyder/browser.py, znoyder/config.yml, znoyder/generator.py, znoyder/mapper.py, znoyder/templater.py
This pull requests includes the following changes.
> Disable functional jobs
This effort has to be rewised and retriaged.
For now let's disable generation of those jobs.
> Add tool to generate projects dict
This commit introduces small tool that can be used
for generating a YAML dictionary with components
and projects assigned to them. It can be later used
for example in Zuul Jobs Board.
> Prevent lines wrapping in generated configs
This commit adds a parameter to the dump function
of PyYAML so it no longer wraps too long lines.
> Minor output improvements
This commit brings small additions to make the user
experience a little better – with more details about
included jobs, warning when no projects were found
(e.g. specified wrong component) and allowing to print
list elements with …
=> General enchancements

znoyder/config.yml
Add missing deps in swiftclient config for py39 tests
to pass successfully.
=> Fix python-swiftclient by adding missing dependencies

.yamllint, znoyder/config.yml, znoyder/generator.py, znoyder/templates/zuul-project-template.j2
This pull request includes the following changes mentioned below.
> Config map cleanups and updates
This commit introduces changes to config map to reflect
recent changes performed during initial verification
of RPM jobs.
> Improve user experience with templates
This commit adds `tojson` filter to the project template,
as with complex extra_commands it turned out to be necessary
in order to generate config with proper syntax.
For easier identification where is eventual failure appears,
the exception catch is added with log containing project name.
=> Config map cleanup

znoyder/config.yml, znoyder/mapper.py
This commit utilizes the copy mechanism of Znoyder and the amazing
shadowing effect in YAML files to generate initial list of jobs
for OSP 17.1 release. Basically, all jobs are copied under the same
name, but with additional `branches` parameter, which overrides
the default value added there from template.
This is not final solution, but for now, as we work on stabilizing
the jobs for OSP 17.0, it would provide us with initial results.
Then, the proper including, adding and overriding will be implemented
instead of the copy map entries.
=> Add initial jobs OSP-17.1

znoyder/config.yml
This commit introduces changes that are identified by CRE team
as required to make the jobs working properly for given projects.
Where applicable, the voting status is also enabled.
Improved also config syntax where alphabetical order was not
preserved after recent change from tox-py39 to rpm-py39.
=> Add recent config changed to Znoyder

znoyder/config.yml
Enabling test-requirements.txt on the rpm job.
That change fixes the job, as seen here: https://code.engineering.redhat.com/gerrit/c/python-cinderclient/+/421404
=> Applying fixes for python-cinderclient

znoyder/config.yml
Removing conflicting rpm package. 
Installing dependencies through pip.
Enabling test-requirements.
=> Fixing python-saharaclient

znoyder/config.yml
Enabling test-requirements.txt
Installing neutron dependencies through pip as the rpm packages do not have the test files required by the job.
=> Fixing python-networking-sfc job

znoyder/config.yml
This PR introduces the installation of missing
packages that made RPM based jobs fail, and
fixing requirements.txt for PrettyTable making
pep8 fail.
=> Fix for python-troveclient

znoyder/config.yml
Enabling test-requirements.txt
After that the job still fails with a 'invalid use_2to3' error which I have no been able to fix. Once this is merged in and I have a build with that I will publish a but ticket for it.
=> Apply first step to fix python-os-brick

znoyder/config.yml
During the analysis of broken jobs I thought that once a job worked we should set it as voting. I was wrong, we can do so but the DFGs should be notified beforehand. On this PR I revert back to non-voting all the jobs that I have worked on.
=> Reverting to non-voting the jobs I covered this past few days

znoyder/config.yml
Instead of manually specifying the RPM test dependencies
and mixing it with pip dependencies, this change sets
allow_test_requirements_txt to true to use it as a source
for the test dependencies (project dependencies are still used
from RPMs).
=> Update oslo-config configuration to use test-reqs

znoyder/config.yml
This change erases the pipeline parameter for the job to be added to both "check" and "gate", thus making it also available on the weekly run.
=> Removing gate constraint to add job to weekly

znoyder/config.yml
Swift was failing on our weekly testing for rpm-based jobs.
The error comes from the "sed" command I used to disable a test.
This will fix the issue and Swift will pass.
=> Fixed "sed" command by removing -r option

znoyder/config.yml
This commit removes the non-voting parameter from jobs
that work properly now after recent efforts of CRE team
to adjust the parameters.
=> Make jobs voting

znoyder/config.yml
This commit introduces a change to Znoyder config map that creates dedicated entries for OSP 17.1 release. This will allow introduction of dedicated adjustments easier than the previous solution allowed (a hack with copy map just for tests).
=> Add dedicated map for OSP 17.1

znoyder/config.yml, znoyder/mapper.py
This commit adjusts Znoyder config and mapper to include only check jobs by default. Then the new copy map entries are added to use the same jobs in gate pipeline as in check pipeline. Thanks to that we can continue work on implementing upstream-like workflow in downstream Gerrit (AKA project gating).
=> Rewise gating jobs

znoyder/config.yml
This resolves issues with running tests for projects that depend on Django/Horizon project and that were somehow missed during initial triaging (basic dependencies).
=> Fix config for 9 projects

znoyder/config.yml
It does not make the job green, but it makes it runnable. There appears project issues that need to be resolved by the DFG.
=> Fix for designate jobs

znoyder/config.yml
This adds missing hostname for openstack-heat-agents and forces installation of dnspython in a wallaby-specific version that is currently not available in repository.
=> Fix for heat-agents and designate

znoyder/config.yml
> Include constraints in Znoyder config
Whenever there is pip install, we should pin the version
of packages to the versions specified for stable/wallaby.
> Update Znoyder config
This will make jobs for heat, nova, swift, tripleo-ansible,
keystoneclient and keystonemiddleware run the tests correctly.
Also the non-voting label for project that was fixed in source
code is removed. Some minor syntax changes to the mapping added.
=> Zuul jobs go brrrrrrrrrrrrrrr

znoyder/config.yml
It turns out I shall remove my copy-paste skill
from my LinkedIn profile – I missed two important
characters in the packages name.
=> Fix typo in config map

znoyder/config.yml
This change modifies the existing workaround for Cinder project to make the pep8 job functional until the appropriate fix will appear in project's source code.
=> Update config for Cinder

znoyder/config.yml
This commit introduces workarounds for Python-AodhClient project to make the unit testing job effective until the necessary changes will be implemeneted in the project's source code.
=> Update config for aodhclient

znoyder/config.yml
All the Component CI jobs were triaged. For all failing jobs, the bug reports were created in BugZilla to report project issues and in some cases the workarounds were added to Znoyder config. With working jobs monitoring, there is no point in keeping the non-voting labels for jobs.
=> Remove non-voting labels

znoyder/config.yml
There is a unit test that does not mock libvirt/libguestfs properly and when those are installed in system, there goes a real call which results with timeout due to no expected response. The test will be fixed in upstream, but for now we just remove the problematic packages that come from spec file.
=> Fix for nova

znoyder/config.yml
Finally, we found a way to make aodh jobs green.
There are two main problems:
1) the tests for postresql are running no matter
we specify backed to MySQL, hence we pass bindep.txt
to install the dependencies,
2) the mysqld file in RHEL containers contains some
extra capabilities requirements in order to run,
which requires container to be deployed with
--privileged or --cap-add SYS_NICE options [1][2].
[1] https://bugs.mysql.com/bug.php?id=91395
[2] https://unix.stackexchange.com/a/303424
=> Fix for aodh

znoyder/config.yml
Drop branches parameter from inherited jobs
Some of the inherited jobs for some reason contained
the specification of trigger branch to master, which
caused issues with our templater engine during jobs
definition generation (we inject our branch pattern
anyway), hence the propsal is to remove such projects.
Inherit py38 as py39 jobs instead of py39 only
I noticed that there are few projects in upstream that
contain definitions for py38, but not for py39 (which is
expected, as py38 was official for stable/wallaby).
Hence the proposal is to take py38 jobs and rename to py39,
which extends the downstream coverage to following projects:
- networking-l2gw
- python-designateclient
- python-keystoneauth1
- python-magnumclient
- python-osc-placement
- python-proliantutils
- python-tooz
The only …
=> Enable additional jobs + minor improvements

znoyder/config.yml
The repositories were synced, the sed is no longer necessary.
=> Remove workarounds for glanceclient pep8 jobs

znoyder/config.yml
We recently enabled tests for additional repositories. This commit introduces necessary fixes to their CI.
=> Fixes for 6 projects

znoyder/config.yml
This commit enables inheriting the non-devstack functional jobs in the following projects:
– cinder
– glance
– nova
– openstack-ironic-inspector
– openstack-ironic-python-agent
– openstack-placement
– python-ironic-inspector-client
– python-magnumclient
– python-osc-placement
– python-ovsdbapp
=> Introduce functional jobs

znoyder/config.py, znoyder/config.yml, znoyder/generator.py, znoyder/tests/test_generator.py
1. Support additional projects
> We need to support some downstream projects that are not directly
> a part of product release, e.g. repositories containing tests
> for specific components and scenarios.
2. Fix for projects with no jobs
> In the current code, if project had jobs for release A,
> but no jobs for release B, then it would result in empty
> list of jobs. This change fixes it.
3. Prepare for OSP 16 support
=> Road to OSP 16 support

znoyder/config.yml
This commit enables additionaly py36 for OSP 17 where the py39 jobs are currently. This is becasue we noticed there are some RHEL8-based puddles still.
For now only periodic jobs to track statuses.
=> Add py36 jobs where py39 are

tox.ini, znoyder/downloader.py, znoyder/tests/test_downloader.py
The rate limit for unauthenticated GitHub requests is really small (60 per hour from a given IP address). Therefore using a personal access token may be necessary in some cases.
=> Add support for GitHub API token

znoyder/config.yml
The base platform for specific releases differs slightly. Hence we shall map jobs corresponding to a given OSP release with a desired nodeset.
=> Pin jobs to specific nodes

znoyder/config.yml
This should match the RHEL version inside the container... I missed that in previous patch.
=> Set properly additional repo for tox jobs

znoyder/config.yml
Covers the following projects:
– cinder
– glance_store
– python-cinderclient
– python-glanceclient
– python-os-brick
– python-swiftclient
– glance
– manila
– python-cinderlib
– python-manilaclient
– neutron
– neutron-lib
– networking-ovn
– python-neutron-tests-tempest
– octavia
The following will be covered in a further patch:
– nova
– swift
=> Mapping for OSP 16 jobs

znoyder/config.yml
The default set -crb repos are missing some packages. I see no reason why not to pick the OSP-related repos directly.
=> Use OSP rhos-release for tox-pep8 jobs

znoyder/config.yml
These are upstream requirements, but downstream OSP only supports the
libvirt and ironic virt drivers. By not unit testing virt drivers that
we don't support, we can simplify our CI.
=> Don't install pypowervm and zVMCloudConnector on 16.1

znoyder/config.yml
There are some packages that require mariadb-devel packages that are referenced in bindep.txt, but those package is not shipped in RHOS repos.
=> ADD CRB repos for tox jobs

znoyder/config.yml
We're slowly starting to see OSP 18.0 backport to Nova downstream. Add
basic functional and unit tests jobs as a sanity check for those
backports. These are copied verbatim from the 17.1 versions (minus the
py36 unit tests job), working on the assumption that we can run them
on RHEL 9.2 for now and everything will be fine.
=> Add OSP 18 jobs for Nova

setup.cfg, tox.ini, znoyder/config.py
As the config.yml file becomes larger and larger,
it would have more sense to introduce multiple
smaller files, e.g. with per OSP release settings.
=> Support splitting config to multiple files

znoyder/config.d/43-override-OSP-18.yml
Nova's code mocks out compute manager's with a mock.DEFAULT. However, the python3-placement-tests requires the python3-mock package – we should remove it to use the built-in standard library.
Then there was error regarding python3-libvirt module imported, while it should not be installed. Hence we remove the package. This resolves the issues with osp-rpm-functional-py39 job.
=> Do not install python3-mock and python3-libvirt

znoyder/config.d/42-override-OSP-17.yml
This makes sure that jobs for python-oslo-config
and tripleo-ansible are working fine.
=> Minor fixes for OSP 17 jobs

znoyder/config.d/43-override-OSP-18.yml
This includes fixes for cinder, heat, oslo.rootwrap and aodhclient.
There were AttributeErrors in PyOpenSSL:
> module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Also for projects that decided to switch to tox4, the --sitepackages option
was deprecated in favor of VIRTUALENV_SYSTEM_SITE_PACKAGES=1.
The tests suite for oslo.rootwrap invokes a new process and in case of tox
with sitepackages it misses the venv-installed packages, hence the project
is installed out of venv as well.
=> More fixes for OSP 18 projects

znoyder/config.d/43-override-OSP-18.yml
Installs the python-osc-placement also system-wide, so the functional test that requires a shell to recognize the proper option in openstack client works.
=> One more fix to OSP 18 jobs

znoyder/config.d/43-override-OSP-18.yml
Turns out it may not be really needed in the end.
This reverts commit a0e616c5478d38c443d42d7994a4012e89a87a12.
=> Revert "Fix ceilometer / OSP 18"

znoyder/config.d/42-override-OSP-17.yml, znoyder/config.d/43-override-OSP-18.yml
The test_discovery_with_libvirt_error case appears to fail randomly, probably depending on the order of the tests execution. After removing the libvirt-libs package the test is simply skipped.
=> Fix ceilometer jobs

znoyder/browser.py, znoyder/cli.py, znoyder/generator.py, znoyder/tests/test_browser.py, znoyder/tests/test_cli.py, znoyder/tests/test_generator.py
This commit adds a logging of files written by generator module. Also minor change of parser options names was done for clarity. Related modification of browser module was also performed.
=> Minor logging and CLI update

znoyder/browser.py, znoyder/cli.py, znoyder/config.d/42-override-OSP-17.yml, znoyder/generator.py, znoyder/tests/test_browser.py, znoyder/tests/test_cli.py, znoyder/tests/test_generator.py
There was a feature backported downstream that requires
a newer version of Neutron-Lib project installed locally.
Thanks to tox-siblings role, we can install the version
of code for liniting specified as dependent repository.
=> Add required project for Neutron / OSP 17.1

znoyder/config.d/42-override-OSP-17.yml
Lack of coffee made me missed the additional parameter should be written for a different job and not under extra `vars` keyword... Thankfully it is weekend coming, but first let's fix it...
=> Fix required project for Neutron / OSP 17.1

.github/workflows/main.yml, .gitignore, README.md, setup.cfg, tox.ini
=> Update for tox4 and minor adjustments

znoyder/config.d/01-branches.yml, znoyder/config.d/31-add-OSP-16.yml
Recently in upstream the stable/train release
was retired branch and became train-eol tag.
=> Update stable/train becoming train-eol

znoyder/config.d/42-override-OSP-17.yml
From now on we want to rely on the package version specified in the spec files instead of PyPi constraints.
=> Use python3-dns in designate / OSP 17.1

znoyder/config.d/42-override-OSP-17.yml
17.0 is no longer supported, not even for CVEs. Remove Nova's 17.0
jobs.
=> Remove Nova 17.0 jobs

znoyder/browser.py, znoyder/tests/test_browser.py
Currently, the urlparse lib is used to find the short repo name from the osp-patches string in distroinfo. This does not work for non-url based strings as `git@gitlab.com:eng/test/repo_name.git`.
This patch is moving to use regex instead of urlparse asuming that the repo name is the string after the last `/` and removing the `.git` if exists. This should cover all kind of strings that may be used in osp-patches field.
Note this is changing slightly the behavior for repos in namespaces. i.e. before this patch if osp-patches is `ssh://server.com/foo/bar`, osp-project would be `foo/bar`. After this patch, it is `bar`. This behavior matches the current usage of this parameter which is used to matcht zuul.project.short_name which points always to the last part, `bar` in the previous case. This …
=> Fix get_packages by osp-project to cover non-url strings

znoyder/browser.py
It turns out that in some cases we have projects in ospinfo that have no downstream forks – in such cases, there is osp-patches key set to empty string and regular expression breaks. Also, the solution with regular expression may lead to ambiguity (is a/b/c matched as a+b/c or a/b+c?), hence we replace that with just basename from path.
=> Use basename instead of regex
