RedHatCRE/znoyder

znoyder/get_project_zuul_files.py

Now the zuul .yaml files are downloaded in the destination folder + project folder:
```
$ -> time python3.10 znoyder/get_project_zuul_files.py --branch=master --project=nova --destination=/tmp/test01
Downloading file .zuul.yaml
real    0m2.359s
user    0m0.198s
sys     0m0.059s
$ -> time python3.10 znoyder/get_project_zuul_files.py --branch=master --project=neutron --destination=/tmp/test01
Downloading file rally.yaml
Downloading file grenade.yaml
Downloading file project.yaml
Downloading file tripleo.yaml
Downloading file base.yaml
Downloading file tempest-multinode.yaml
Downloading file tempest-singlenode.yaml
real    0m3.072s
user    0m0.435s
sys     0m0.151s
```
```
$ -> tree -a /tmp/test01/
/tmp/test01/
├── neutron
│   └── zuul.d
│       ├── base.yaml
│       ├── grenade.yaml
│ …
```

Update: Change downloaded files destination folder

---

README.md
requirements.txt
setup.cfg
shperer/cli.py
shperer/lib/exceptions.py
shperer/lib/logger.py
shperer/lib/util.py
shperer/lib/zuul.py

shperer is a new CLI which allows to discover jobs and templates
which are associated with a particular project.

CLI to discover jobs in a particular project

---

znoyder/templater.py

Fix which ensures job is listed only once within one trigger type.

Make sure job is liste only once

---

znoyder/templater.py
znoyder/templates/empty-zuul-project.j2
znoyder/templates/zuul-project.j2

Nit adjustment that allows zuul to pass config check.

Small adjustment to the zuul-project template.

---

znoyder/generator.py
znoyder/templater.py
znoyder/templates/project-config.j2

Project config links between a project template and a project.
Also, added an option to aggregate all templates in one file instead
of each template in its own file.

Add a template for project config

---

.gitignore
test-requirements.txt
tox.ini

Update tox and add pre-commit hook for more complete testing and linting

Add files for basic ci (lint, test, coverage)

---

znoyder/browser.py
znoyder/cli.py
znoyder/downloader.py
znoyder/finder.py
znoyder/generator.py
znoyder/templater.py

Move all cli parsing into the cli module to decouple command logic from
argument parsing

Refactor command line parsing to cli module

---

znoyder/templater.py

This is the first implementation on this issue.
Any suggestions are greatly appreciated.

Error catch on generation implemented

---

tests/__init__.py
tests/test_cli.py

Add unit tests for cli module. CI checks will fail due to low coverage of the
commands moudules.

Add unit test for cli module

---

tests/test_generator.py
znoyder/generator.py

As this module is still not definitive and is bound to change, I have avoided testing the 'main' function yet. Coverage will not be as high because this only covers testing of the surrounding functions. Additionally, I have added a small fix to have the tests pass correctly.

Testing the 'generator' module.

---

tests/test_generator.py
tox.ini
znoyder/cli.py
znoyder/generator.py
znoyder/templater.py

This commit introduces minor changes to existing code, such as:
– imports reorder,
– fix in generator tests that imported wrong entry,
– shared venv in tox environments.

Minor code cleanups

---

tests/test_mapper.py
tests/test_templater.py
znoyder/config.yml
znoyder/mapper.py
znoyder/templater.py
znoyder/templates/zuul-project.j2

- Implement jobs override mechanism
- Consider jobs properties in templater
- Update config map with initial values

Part 2 of jobs mapper implementation

---

znoyder/config.yml

Until rhbz#2069099 is resolved.

Set neutron osp 17 as non-voting

---

znoyder/config.yml

- Remove duplicated exclude entries
- Exclude Storage DFG jobs

Update exclude map

---

znoyder/config.yml

Until rhbz#2052499 is resolved.

Set keystone osp17 as non-voting

---

znoyder/config.yml

The rhbz#2069099 has been resolved.

Revert non-voting for neutron jobs

---

znoyder/config.yml

For some reason this project was missing in config.yml
though the project should be tested in OSP 17.0

Add python-networking-baremetal to config.yml

---

znoyder/config.yml

Adding overrides to tripleo-ansible so that the job passes successfully.

Fixing tripleo-ansible project

---

znoyder/config.yml

The job can be seen working here: https://code.engineering.redhat.com/gerrit/c/python-scciclient/+/421409

Fixing job python-scciclient

---

znoyder/config.yml

Getting the job to install test dependencies in order for it to work. Proof in here: https://code.engineering.redhat.com/gerrit/c/python-manilaclient/+/421391
I also removed a couple of useless vars from the job I fixed before.

Fixing python-manilaclient job

---

znoyder/config.yml

Allowing test requirements for the job to pass, this can be seen here: https://code.engineering.redhat.com/gerrit/c/glance/+/421475

Fixing 'glance' job

---

znoyder/config.yml

Install missing dependencies
Downgrade virtualenv in tox.ini

Fix rpm and tox for glance_store

---

znoyder/config.yml

based on abandoned commits to osp-internal-jobs.

Updates for python-keystonemiddleware and nova

---

znoyder/config.yml

On this change I corrected the way we disable a particular unittest on swift.
This change should future proof it against changes to the testing.

changed disabling test method

---

znoyder/config.yml

This commit adds workaround for two projects
to make the jobs passing.

Update config for os-vif and glanceclient

---

znoyder/config.yml

Minor fix for ovsdbapp

---

znoyder/config.yml
znoyder/generator.py
znoyder/tests/test_generator.py

– Add support for multiple upstream releases
– Add missing mapping for functional jobs

Improve support for multiple releases

---

znoyder/config.yml

Config for Nova @ OSP 16

---

znoyder/config.yml

I am not sure why CDN repos were picked in the first place.

Switch from CDN to regular repos

---

znoyder/config.yml

This enables functional jobs for OSP 17
and all basic jobs for OSP 16.

Enable additional jobs for swift

---

znoyder/config.yml

Tested as weekly jobs, we have enough successes
to enable all these jobs within the check pipeline.

OSP 17 / RHEL 8 jobs enablement

---

znoyder/downloader.py

Display full paths instead of just names so we know what is processed in case of multiple releases.

Minor update to downloader logs

---

znoyder/config.d/31-add-OSP-16.yml

Includes the changes we are missing in downstream forks:
– https://review.opendev.org/c/openstack/cinderlib/+/850756
– https://review.opendev.org/c/openstack/python-manilaclient/+/682318

Fix OSP 16.1 projects

---

znoyder/config.d/43-override-OSP-18.yml

Fix OSP 18 functional tests

---

znoyder/config.d/43-override-OSP-18.yml

Adds missing elements for glance_store, octaviaclient and os-vif.

Fix OSP 18 projects

---

znoyder/config.d/43-override-OSP-18.yml

There is a new downstream-only dependency required now

Add dep for aodh/OSP18
